const phonicsGroups = [
    { name: '第 1 組 (SATIPN)', letters: ['S','A','T','I','P','N'] },
    { name: '第 2 組 (CKEHRMD)', letters: ['C','K','E','H','R','M','D'] },
    { name: '第 3 組 (GOULFB)', letters: ['G','O','U','L','F','B'] },
    { name: '第 4 組 (JVWXYZQ)', letters: ['J','V','W','X','Y','Z','Q'] }
];

const letterStrokes = {
    // A: left slant, right slant, crossbar
    'A': [[150,40,90,220],[150,40,210,220],[110,145,190,145]],
    // B: stem → top bowl → bottom bowl (bowl1 end = bowl2 start)
    'B': [[100,40,100,220],[100,40,168,40,192,78,168,112,100,112],[100,112,172,112,198,158,172,220,100,220]],
    // C: one open curve
    'C': [[205,80,175,42,125,38,82,88,78,150,88,205,130,230,180,222,208,185]],
    // D: stem → big curve (curve starts at stem top)
    'D': [[100,40,100,220],[100,40,168,40,208,90,208,170,168,220,100,220]],
    // E: stem → top → mid → bottom
    'E': [[100,40,100,220],[100,40,195,40],[100,130,175,130],[100,220,195,220]],
    // F: stem → top → mid
    'F': [[100,40,100,220],[100,40,195,40],[100,130,170,130]],
    // G: C-curve → inward bar (bar starts at curve end)
    'G': [[205,80,175,42,125,38,82,88,78,150,88,205,130,230,180,222,205,185,205,150],[205,150,145,150]],
    // H: left stem → right stem → crossbar
    'H': [[100,40,100,220],[200,40,200,220],[100,130,200,130]],
    // I: top bar → vertical (from bar center) → bottom bar
    'I': [[100,40,200,40],[150,40,150,220],[100,220,200,220]],
    // J: top bar → hook from bar center
    'J': [[110,40,230,40],[170,40,170,175,150,220,115,220,95,190]],
    // K: stem → upper arm → lower arm (arms meet on stem)
    'K': [[100,40,100,220],[190,40,100,130],[100,130,190,220]],
    // L: down then right (one stroke)
    'L': [[110,40,110,220,205,220]],
    // M: left down → to middle → to top-right → right down (2→3→4 connected)
    'M': [[80,40,80,220],[80,40,150,145],[150,145,220,40],[220,40,220,220]],
    // N: left down → diagonal → right up (diagonal end = right stem start)
    'N': [[85,40,85,220],[85,40,215,220],[215,220,215,40]],
    // O: closed oval
    'O': [[150,38,95,70,78,130,90,195,150,232,210,195,222,130,205,70,150,38]],
    // P: stem → bowl
    'P': [[100,40,100,220],[100,40,168,40,198,80,168,125,100,125]],
    // Q: oval → tail (tail from lower-right of oval)
    'Q': [[150,38,95,70,78,130,90,195,150,232,210,195,222,130,205,70,150,38],[175,185,230,235]],
    // R: stem → bowl → leg (bowl end ≈ leg start on stem)
    'R': [[100,40,100,220],[100,40,168,40,198,80,168,125,100,125],[100,125,195,220]],
    // S: one continuous curve
    'S': [[200,75,160,40,110,45,90,85,120,120,180,145,205,180,180,220,125,225,95,195]],
    // T: top bar → stem from center
    'T': [[75,40,225,40],[150,40,150,220]],
    // U: one cup
    'U': [[95,40,95,165,115,210,150,228,185,210,205,165,205,40]],
    // V: one stroke
    'V': [[80,40,150,220,220,40]],
    // W: one stroke
    'W': [[70,40,110,220,150,110,190,220,230,40]],
    // X: two diagonals
    'X': [[85,40,215,220],[215,40,85,220]],
    // Y: left → right into crotch → stem down (2→3 connected at crotch)
    'Y': [[80,40,150,125],[220,40,150,125],[150,125,150,220]],
    // Z: top → diagonal → bottom (one continuous stroke)
    'Z': [[80,40,220,40,80,220,220,220]]
};


// 精選具象字彙 + 合體字（air+plane 呢類）
const rawD = [
    ['A','ant','🐜',[['æ','a'],['n','n'],['t','t']],'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRTqZsTppo-y06ojxPqRMtZYTLTxYptA0k0o_RxZxEhuc-JYo0uOqHo5AQsKGl06czjVwr3m-l55-MrtQ8'],
    ['A','axe','🪓',[['æ','a'],['k s','xe']]],
    ['A','arm','💪',[['ɑː','ar'],['m','m']]],
    ['A','art','🎨',[['ɑː','ar'],['t','t']]],
    ['A','airplane','✈️',[['eə','air'],['pleɪn','plane']]],
    ['B','bug','🐛',[['b','b'],['ʌ','u'],['g','g']],'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQhUl7djA2u2Toee8Y9oZNTf2rog3BP0zIJMeV8t1q_TI8HQDWp0ha_UKpKS9DvkZWkUEWM_0JwfAZF6SA'],
    ['B','bat','🦇',[['b','b'],['æ','a'],['t','t']]],
    ['B','bed','🛏️',[['b','b'],['ɛ','e'],['d','d']]],
    ['B','bus','🚌',[['b','b'],['ʌ','u'],['s','s']]],
    ['B','bicycle','🚲',[['baɪ','bi'],['saɪkəl','cycle']]],
    ['C','cat','🐱',[['k','c'],['æ','a'],['t','t']],'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTY5Ow415BCLiENvY-XltdMQwjw-ZEHqV12EXDOIk22qkrOwpaaClbWXnGSWrQKfeizSqc7xJkpCLSXdB8'],
    ['C','cup','🥤',[['k','c'],['ʌ','u'],['p','p']]],
    ['C','car','🚗',[['k','c'],['ɑː','ar']]],
    ['C','cap','🧢',[['k','c'],['æ','a'],['p','p']]],
    ['C','cupcake','🧁',[['kʌp','cup'],['keɪk','cake']]],
    ['D','dog','🐶',[['d','d'],['ɒ','o'],['g','g']],'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQxNXQhyLhFHqkHzUr19pCRHNWVY05Fh373O0jxRxMjgWj_dfvVLVmLnUJLISk6AdTj1BmhVbHSHA0J5UQ'],
    ['D','dad','🧔',[['d','d'],['æ','a'],['d','d']]],
    ['D','dot','⚫',[['d','d'],['ɒ','o'],['t','t']]],
    ['D','duck','🦆',[['d','d'],['ʌ','u'],['k','ck']]],
    ['E','egg','🥚',[['ɛ','e'],['g','gg']],'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQCE-9NVZEDxG3ekJDIPeyfYLCBWuatFqJyB6IO3nYGgIp9Q3DcTuI7vGeq0SNEka7c3pjrIbkHdmcXE0A'],
    ['E','elf','🧝',[['ɛ','e'],['l','l'],['f','f']]],
    ['E','elk','🦌',[['ɛ','e'],['l','l'],['k','k']]],
    ['E','eat','🍽️',[['iː','ea'],['t','t']]],
    ['F','fox','🦊',[['f','f'],['ɒ','o'],['k s','x']],'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcR5UwT41ltm42FcjXeocyAyPdTt1AmUUd2yXos8fYkCU2FWDOt3GHX0zZA1OkTzeYicm3NW2H7Zme7PzS4'],
    ['F','fan','🪭',[['f','f'],['æ','a'],['n','n']]],
    ['F','fin','🐟',[['f','f'],['ɪ','i'],['n','n']]],
    ['F','fog','🌫️',[['f','f'],['ɒ','o'],['g','g']]],
    ['F','football','⚽',[['fʊt','foot'],['bɔːl','ball']]],
    ['G','gum','🫧',[['g','g'],['ʌ','u'],['m','m']],'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSttm5fKjDTpwXf6ZPUelc9pt2UzOjgySXzuYRvqYi13HT8M5zpBK_AtpHHGV_AnshxUO5v3TkYvwDTtYc'],
    ['G','gas','⛽',[['g','g'],['æ','a'],['s','s']]],
    ['G','gift','🎁',[['g','g'],['ɪ','i'],['f','f'],['t','t']]],
    ['G','goat','🐐',[['g','g'],['oʊ','oa'],['t','t']]],
    ['H','hat','🎩',[['h','h'],['æ','a'],['t','t']],'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRA9ZgNqzvABD4as-ZwcdLsr6d86yWaIQmFbkm1_Rq8vry8rR0yDtxxC5sj0FboMzsJDxm8hFFd-b3BPJw'],
    ['H','hen','🐔',[['h','h'],['ɛ','e'],['n','n']]],
    ['H','hit','🥊',[['h','h'],['ɪ','i'],['t','t']]],
    ['H','hop','🦘',[['h','h'],['ɒ','o'],['p','p']]],
    ['I','ink','✒️',[['ɪ','i'],['ŋ k','nk']],'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTEXL-Ev2FmxrLxkIaoOu0fmjtQLhnbSzQFh1gLLChUBoy8VfoLi7YuYUNeOMqT7qPqT7Hvqd4fICCSMbA'],
    ['I','ice','🧊',[['aɪ','i'],['s','ce']]],
    ['I','ill','🤒',[['ɪ','i'],['l','ll']]],
    ['I','insect','🐞',[['ɪn','in'],['sɛkt','sect']]],
    ['J','jam','🫙',[['dʒ','j'],['æ','a'],['m','m']],'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTDM_lMgpzKbhrj_NAn55jRkq70QgcdVMGth6vRoZDI5iv1H9q5lbkWgQ-55pheVXS_MK0TKDWvRqntR9Y'],
    ['J','jet','✈️',[['dʒ','j'],['ɛ','e'],['t','t']]],
    ['J','jog','🚶',[['dʒ','j'],['ɒ','o'],['g','g']]],
    ['J','jug','🫙',[['dʒ','j'],['ʌ','u'],['g','g']]],
    ['K','kid','👦',[['k','k'],['ɪ','i'],['d','d']],'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQAfPmFNM3kpCpySAIbjUnuW6y1Tp7Owahxz1SlMh745qhcgbtjAtbJKV7tQ3BlQBnBXxkDR16IbVp7Uno'],
    ['K','kit','🧰',[['k','k'],['ɪ','i'],['t','t']]],
    ['K','keg','🛢️',[['k','k'],['ɛ','e'],['g','g']]],
    ['K','king','🤴',[['k','k'],['ɪ','i'],['ŋ','ng']]],
    ['L','log','🪵',[['l','l'],['ɒ','o'],['g','g']],'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcT_0QFKA_34cABAQUsqNFJWLxM6TAid_QI7F8X6BZqIpmvIv6-OW0YkJFbr-a9rh7CPR4v6BQpSMWUtPqA'],
    ['L','leg','🦵',[['l','l'],['ɛ','e'],['g','g']]],
    ['L','lip','👄',[['l','l'],['ɪ','i'],['p','p']]],
    ['L','lamp','💡',[['l','l'],['æ','a'],['m','m'],['p','p']]],
    ['M','map','🗺️',[['m','m'],['æ','a'],['p','p']],'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRNi0R0rSCZlU0LlXWFvIeZtCXvg1JGIOe_El_kQrfkfuzPamx-WUeOrza7_6pSMqs6Zzr-qZSPAKDRm5Q'],
    ['M','man','👨',[['m','m'],['æ','a'],['n','n']]],
    ['M','mat','🧘',[['m','m'],['æ','a'],['t','t']]],
    ['M','mug','☕',[['m','m'],['ʌ','u'],['g','g']]],
    ['N','net','🥅',[['n','n'],['ɛ','e'],['t','t']],'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQEwVNmghxotUlk7i1K-tn6PKsPDstqTyfEvNtikmeGuy6OzKcBMHjD3B6Qblf9SgNqFD3inN6mhkiBszM'],
    ['N','nut','🥜',[['n','n'],['ʌ','u'],['t','t']]],
    ['N','nap','😴',[['n','n'],['æ','a'],['p','p']]],
    ['N','nail','🔩',[['n','n'],['eɪ','ai'],['l','l']]],
    ['O','ox','🐂',[['ɒ','o'],['k s','x']],'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcThnW2IKxgUaso2iv-eUTnXj0AbxAgZczA1dZD6uOHfbHyZ6yg7atG3GERxvwtEcsZcOVpJChohv-AcOcM'],
    ['O','owl','🦉',[['aʊ','ow'],['l','l']]],
    ['O','oil','🛢️',[['ɔɪ','oi'],['l','l']]],
    ['O','oak','🌳',[['oʊ','oa'],['k','k']]],
    ['P','pig','🐷',[['p','p'],['ɪ','i'],['g','g']],'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQKeXVO6_P7iX_M8qKtcMiE_6tX-jp5F1DMc8OS4t9tagZiAlKCTwpzbzWLNhM5VI-EDr_WYzEnWuvi6jI'],
    ['P','pan','🍳',[['p','p'],['æ','a'],['n','n']]],
    ['P','pot','🍲',[['p','p'],['ɒ','o'],['t','t']]],
    ['P','pen','🖊️',[['p','p'],['ɛ','e'],['n','n']]],
    ['Q','queen','👑',[['k w','qu'],['iː','ee'],['n','n']],'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcS7OekNWBK0RgpM6fRVHR9i8OJiqpUkKAk1zv_UpAQovoGyeWQBIejBjBxm2Xw-Tf2xno4I04y6BeJH3I0'],
    ['Q','quack','🦆',[['k w','qu'],['æ','a'],['k','ck']]],
    ['Q','quiz','📝',[['k w','qu'],['ɪ','i'],['z','z']]],
    ['Q','quilt','🛏️',[['k w','qu'],['ɪ','i'],['l','l'],['t','t']]],
    ['R','rat','🐀',[['r','r'],['æ','a'],['t','t']],'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQu0L6o30Effc2t3NFJlldZ9o_V2UqrhtX_cWGeg5bAuQj-CWXYMG8Y1lb8XuqxIE-gG2tGiXhLIDdS2Bw'],
    ['R','red','🟥',[['r','r'],['ɛ','e'],['d','d']]],
    ['R','run','🏃',[['r','r'],['ʌ','u'],['n','n']]],
    ['R','rug','🧶',[['r','r'],['ʌ','u'],['g','g']]],
    ['R','rainbow','🌈',[['reɪn','rain'],['boʊ','bow']]],
    ['S','sun','☀️',[['s','s'],['ʌ','u'],['n','n']],'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQNyhYS-HfjJZP5MiJql07BHXUYre7kbwUIPvzDu1dRTLjXFgFeIZ6G4fU_ML20vtHByLfgXpjZSXvTa0s'],
    ['S','sad','😢',[['s','s'],['æ','a'],['d','d']]],
    ['S','sit','🪑',[['s','s'],['ɪ','i'],['t','t']]],
    ['S','six','6️⃣',[['s','s'],['ɪ','i'],['k s','x']]],
    ['S','sunflower','🌻',[['sʌn','sun'],['flaʊər','flower']]],
    ['T','toy','🧸',[['t','t'],['ɔɪ','oy']]],
    ['T','ten','🔟',[['t','t'],['ɛ','e'],['n','n']]],
    ['T','tap','🚰',[['t','t'],['æ','a'],['p','p']]],
    ['T','tub','🛁',[['t','t'],['ʌ','u'],['b','b']]],
    ['T','telephone','☎️',[['tɛli','tele'],['foʊn','phone']]],
    ['U','up','⬆️',[['ʌ','u'],['p','p']]],
    ['U','urn','🏺',[['ɜː','ur'],['n','n']]],
    ['U','ufo','🛸',[['juː','U'],['ɛf','F'],['oʊ','O']]],
    ['U','uncle','👨',[['ʌ','u'],['ŋ','n'],['k','c'],['əl','le']]],
    ['V','van','🚐',[['v','v'],['æ','a'],['n','n']],'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQ3ABZcWjPe2pk3Tv-MtkKkgswf96awAFM6XmFefBZgLK_iVgyASs3682A1K-0RKsidewn13s0bDxrUusM'],
    ['V','vet','🩺',[['v','v'],['ɛ','e'],['t','t']]],
    ['V','vine','🌿',[['v','v'],['aɪ','i'],['n','ne']]],
    ['V','vest','🦺',[['v','v'],['ɛ','e'],['s','s'],['t','t']]],
    ['W','web','🕸️',[['w','w'],['ɛ','e'],['b','b']],'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQzSoXPhCnWP5WguUR3ItXofRAFHiFtL6-0ZrUu65dEJ3uuC1h_2_MetLtPlwT6QB4Q9EbTT431judW0s8'],
    ['W','wig','💇‍♀️',[['w','w'],['ɪ','i'],['g','g']]],
    ['W','wet','💦',[['w','w'],['ɛ','e'],['t','t']]],
    ['W','win','🏆',[['w','w'],['ɪ','i'],['n','n']]],
    ['X','box','📦',[['b','b'],['ɒ','o'],['k s','x']],'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTWHlMZTybVuOeL3MEU3IBT_9aJx_lWWWui0tFrh4fMWl8uCu_70vCRm4L7qH2BMdq7pfZalNKmEXhr-gg'],
    ['X','fox','🦊',[['f','f'],['ɒ','o'],['k s','x']]],
    ['X','six','6️⃣',[['s','s'],['ɪ','i'],['k s','x']]],
    ['X','wax','🕯️',[['w','w'],['æ','a'],['k s','x']]],
    ['Y','yam','🍠',[['j','y'],['æ','a'],['m','m']],'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTvn_X48yY-erqiLzYg1zUYU_-6R24CdFaVo6iq6cKECcJ-necfuSuIeFFIeGBsO6BFG5HH8Ot2FjX0fYU'],
    ['Y','yak','🦬',[['j','y'],['æ','a'],['k','k']]],
    ['Y','yell','🗣️',[['j','y'],['ɛ','e'],['l','ll']]],
    ['Y','yolk','🟡',[['j','y'],['oʊ','ol'],['k','k']]],
    ['Z','zip','🤐',[['z','z'],['ɪ','i'],['p','p']],'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQzR1g7zbgxsmYBH_wQxH1Kbg1xop5bjoFvZDA_mLrJ8ND3hi7sq1nxmEjG3c7fKMtDk2tIGemgaZAYSUo'],
    ['Z','zoo','🦁',[['z','z'],['uː','oo']]],
    ['Z','zebra','🦓',[['z','z'],['iː','e'],['b','b'],['r','r'],['ə','a']]],
    ['Z','zero','0️⃣',[['z','z'],['ɪə','e'],['r','r'],['oʊ','o']]]
];

const rawMore = [
    ['A','apple','🍎',[['a','a'],['p','p'],['p','p'],['l','l'],['e','e']],'蘋果'],
    ['A','alien','👽',[['a','a'],['l','l'],['i','i'],['e','e'],['n','n']],'外星人'],
    ['A','arrow','➡️',[['ar','ar'],['r','r'],['ow','ow']],'箭咀'],
    ['A','ankle','🦶',[['a','a'],['n','n'],['k','k'],['l','l'],['e','e']],'腳踝'],
    ['A','ambulance','🚑',[['a','a'],['m','m'],['b','b'],['u','u'],['l','l'],['a','a'],['n','n'],['c','c'],['e','e']],'救護車'],
    ['A','alligator','🐊',[['a','a'],['l','l'],['l','l'],['i','i'],['g','g'],['a','a'],['t','t'],['or','or']],'鱷魚'],
    ['A','astronaut','👨‍🚀',[['a','a'],['s','s'],['t','t'],['r','r'],['o','o'],['n','n'],['a','a'],['u','u'],['t','t']],'太空人'],
    ['A','apron','🥼',[['a','a'],['p','p'],['r','r'],['o','o'],['n','n']],'圍裙'],
    ['A','anchor','⚓',[['a','a'],['n','n'],['ch','ch'],['or','or']],'錨'],
    ['B','ball','⚽',[['b','b'],['a','a'],['l','l'],['l','l']],'波'],
    ['B','bag','👜',[['b','b'],['a','a'],['g','g']],'袋'],
    ['B','bear','🐻',[['b','b'],['ea','ea'],['r','r']],'熊'],
    ['B','bee','🐝',[['b','b'],['ee','ee']],'蜜蜂'],
    ['B','bird','🐦',[['b','b'],['ir','ir'],['d','d']],'雀'],
    ['B','boat','🚤',[['b','b'],['oa','oa'],['t','t']],'船'],
    ['B','book','📖',[['b','b'],['oo','oo'],['k','k']],'書'],
    ['B','bread','🍞',[['b','b'],['r','r'],['ea','ea'],['d','d']],'麵包'],
    ['B','baby','👶',[['b','b'],['a','a'],['b','b'],['y','y']],'寶寶'],
    ['B','banana','🍌',[['b','b'],['a','a'],['n','n'],['a','a'],['n','n'],['a','a']],'香蕉'],
    ['B','balloon','🎈',[['b','b'],['a','a'],['l','l'],['l','l'],['oo','oo'],['n','n']],'氣球'],
    ['B','barn','🏚️',[['b','b'],['ar','ar'],['n','n']],'穀倉'],
    ['B','bell','🔔',[['b','b'],['e','e'],['l','l'],['l','l']],'鐘'],
    ['B','berry','🍓',[['b','b'],['er','er'],['r','r'],['y','y']],'莓'],
    ['C','cake','🎂',[['c','c'],['a','a'],['k','k'],['e','e']],'蛋糕'],
    ['C','cow','🐮',[['c','c'],['ow','ow']],'牛'],
    ['C','corn','🌽',[['c','c'],['or','or'],['n','n']],'粟米'],
    ['C','coat','🧥',[['c','c'],['oa','oa'],['t','t']],'大衣'],
    ['C','coin','🪙',[['c','c'],['oi','oi'],['n','n']],'硬幣'],
    ['C','cloud','☁️',[['c','c'],['l','l'],['ou','ou'],['d','d']],'雲'],
    ['C','clock','⏰',[['c','c'],['l','l'],['o','o'],['ck','ck']],'鐘'],
    ['C','crab','🦀',[['c','c'],['r','r'],['a','a'],['b','b']],'蟹'],
    ['C','crown','👑',[['c','c'],['r','r'],['ow','ow'],['n','n']],'皇冠'],
    ['C','candy','🍬',[['c','c'],['a','a'],['n','n'],['d','d'],['y','y']],'糖'],
    ['C','carrot','🥕',[['c','c'],['ar','ar'],['r','r'],['o','o'],['t','t']],'紅蘿蔔'],
    ['C','chair','🪑',[['ch','ch'],['ai','ai'],['r','r']],'椅'],
    ['C','chicken','🐥',[['ch','ch'],['i','i'],['ck','ck'],['e','e'],['n','n']],'雞'],
    ['C','cookie','🍪',[['c','c'],['oo','oo'],['k','k'],['i','i'],['e','e']],'曲奇'],
    ['D','door','🚪',[['d','d'],['oo','oo'],['r','r']],'門'],
    ['D','drum','🥁',[['d','d'],['r','r'],['u','u'],['m','m']],'鼓'],
    ['D','desk','🖥️',[['d','d'],['e','e'],['s','s'],['k','k']],'書檯'],
    ['D','dish','🍽️',[['d','d'],['i','i'],['sh','sh']],'碟'],
    ['D','doll','🪆',[['d','d'],['o','o'],['l','l'],['l','l']],'公仔'],
    ['D','deer','🦌',[['d','d'],['ee','ee'],['r','r']],'鹿'],
    ['D','dinosaur','🦕',[['d','d'],['i','i'],['n','n'],['o','o'],['s','s'],['a','a'],['ur','ur']],'恐龍'],
    ['D','donut','🍩',[['d','d'],['o','o'],['n','n'],['u','u'],['t','t']],'冬甩'],
    ['D','dress','👗',[['d','d'],['r','r'],['e','e'],['s','s'],['s','s']],'裙'],
    ['D','dragon','🐉',[['d','d'],['r','r'],['a','a'],['g','g'],['o','o'],['n','n']],'龍'],
    ['E','ear','👂',[['ea','ea'],['r','r']],'耳'],
    ['E','eye','👁️',[['e','e'],['y','y'],['e','e']],'眼'],
    ['E','elbow','💪',[['e','e'],['l','l'],['b','b'],['ow','ow']],'手踭'],
    ['E','engine','🚂',[['e','e'],['ng','ng'],['i','i'],['n','n'],['e','e']],'引擎'],
    ['E','envelope','✉️',[['e','e'],['n','n'],['v','v'],['e','e'],['l','l'],['o','o'],['p','p'],['e','e']],'信封'],
    ['E','elephant','🐘',[['e','e'],['l','l'],['e','e'],['ph','ph'],['a','a'],['n','n'],['t','t']],'大象'],
    ['E','eagle','🦅',[['ea','ea'],['g','g'],['l','l'],['e','e']],'鷹'],
    ['E','earth','🌍',[['ea','ea'],['r','r'],['th','th']],'地球'],
    ['F','fish','🐟',[['f','f'],['i','i'],['sh','sh']],'魚'],
    ['F','frog','🐸',[['f','f'],['r','r'],['o','o'],['g','g']],'青蛙'],
    ['F','farm','🚜',[['f','f'],['ar','ar'],['m','m']],'農場'],
    ['F','fire','🔥',[['f','f'],['ir','ir'],['e','e']],'火'],
    ['F','fork','🍴',[['f','f'],['or','or'],['k','k']],'叉'],
    ['F','fruit','🍇',[['f','f'],['r','r'],['u','u'],['i','i'],['t','t']],'生果'],
    ['F','flag','🚩',[['f','f'],['l','l'],['a','a'],['g','g']],'旗'],
    ['F','flower','🌸',[['f','f'],['l','l'],['ow','ow'],['er','er']],'花'],
    ['F','foot','🦶',[['f','f'],['oo','oo'],['t','t']],'腳'],
    ['F','family','👨‍👩‍👧',[['f','f'],['a','a'],['m','m'],['i','i'],['l','l'],['y','y']],'家庭'],
    ['F','feather','🪶',[['f','f'],['ea','ea'],['th','th'],['er','er']],'羽毛'],
    ['G','girl','👧',[['g','g'],['ir','ir'],['l','l']],'女仔'],
    ['G','grape','🍇',[['g','g'],['r','r'],['a','a'],['p','p'],['e','e']],'提子'],
    ['G','grass','🌿',[['g','g'],['r','r'],['a','a'],['s','s'],['s','s']],'草'],
    ['G','green','🟩',[['g','g'],['r','r'],['ee','ee'],['n','n']],'綠色'],
    ['G','guitar','🎸',[['g','g'],['u','u'],['i','i'],['t','t'],['ar','ar']],'結他'],
    ['G','glue','🧴',[['g','g'],['l','l'],['u','u'],['e','e']],'膠水'],
    ['G','glove','🧤',[['g','g'],['l','l'],['o','o'],['v','v'],['e','e']],'手套'],
    ['G','gorilla','🦍',[['g','g'],['or','or'],['i','i'],['l','l'],['l','l'],['a','a']],'大猩猩'],
    ['G','garden','🏡',[['g','g'],['ar','ar'],['d','d'],['e','e'],['n','n']],'花園'],
    ['H','hand','✋',[['h','h'],['a','a'],['n','n'],['d','d']],'手'],
    ['H','house','🏠',[['h','h'],['ou','ou'],['s','s'],['e','e']],'屋'],
    ['H','horse','🐴',[['h','h'],['or','or'],['s','s'],['e','e']],'馬'],
    ['H','heart','❤️',[['h','h'],['ea','ea'],['r','r'],['t','t']],'心'],
    ['H','hill','⛰️',[['h','h'],['i','i'],['l','l'],['l','l']],'山'],
    ['H','hammer','🔨',[['h','h'],['a','a'],['m','m'],['m','m'],['er','er']],'鎚'],
    ['H','honey','🍯',[['h','h'],['o','o'],['n','n'],['e','e'],['y','y']],'蜜糖'],
    ['H','helicopter','🚁',[['h','h'],['e','e'],['l','l'],['i','i'],['c','c'],['o','o'],['p','p'],['t','t'],['er','er']],'直升機'],
    ['H','hippo','🦛',[['h','h'],['i','i'],['p','p'],['p','p'],['o','o']],'河馬'],
    ['H','hook','🪝',[['h','h'],['oo','oo'],['k','k']],'鈎'],
    ['I','igloo','🛖',[['i','i'],['g','g'],['l','l'],['oo','oo']],'冰屋'],
    ['I','island','🏝️',[['i','i'],['s','s'],['l','l'],['a','a'],['n','n'],['d','d']],'島'],
    ['I','iron','👔',[['ir','ir'],['o','o'],['n','n']],'熨斗'],
    ['I','ivy','🌱',[['i','i'],['v','v'],['y','y']],'常春藤'],
    ['I','iguana','🦎',[['i','i'],['g','g'],['u','u'],['a','a'],['n','n'],['a','a']],'鬣蜥'],
    ['I','icecream','🍦',[['i','i'],['c','c'],['e','e'],['c','c'],['r','r'],['ea','ea'],['m','m']],'雪糕'],
    ['I','idea','💡',[['i','i'],['d','d'],['ea','ea']],'主意'],
    ['J','juice','🧃',[['j','j'],['u','u'],['i','i'],['c','c'],['e','e']],'果汁'],
    ['J','jump','🤾',[['j','j'],['u','u'],['m','m'],['p','p']],'跳'],
    ['J','jacket','🧥',[['j','j'],['a','a'],['ck','ck'],['e','e'],['t','t']],'外套'],
    ['J','jeep','🚙',[['j','j'],['ee','ee'],['p','p']],'吉普車'],
    ['J','jelly','🍮',[['j','j'],['e','e'],['l','l'],['l','l'],['y','y']],'啫喱'],
    ['J','jungle','🌴',[['j','j'],['u','u'],['ng','ng'],['l','l'],['e','e']],'叢林'],
    ['J','jar','🫙',[['j','j'],['ar','ar']],'玻璃樽'],
    ['K','kite','🪁',[['k','k'],['i','i'],['t','t'],['e','e']],'風箏'],
    ['K','key','🔑',[['k','k'],['e','e'],['y','y']],'鎖匙'],
    ['K','koala','🐨',[['k','k'],['oa','oa'],['l','l'],['a','a']],'樹熊'],
    ['K','ketchup','🍅',[['k','k'],['e','e'],['t','t'],['ch','ch'],['u','u'],['p','p']],'茄汁'],
    ['K','kitchen','🍳',[['k','k'],['i','i'],['t','t'],['ch','ch'],['e','e'],['n','n']],'廚房'],
    ['K','kangaroo','🦘',[['k','k'],['a','a'],['ng','ng'],['ar','ar'],['oo','oo']],'袋鼠'],
    ['K','kiwi','🥝',[['k','k'],['i','i'],['w','w'],['i','i']],'奇異果'],
    ['L','leaf','🍃',[['l','l'],['ea','ea'],['f','f']],'葉'],
    ['L','lion','🦁',[['l','l'],['i','i'],['o','o'],['n','n']],'獅子'],
    ['L','lemon','🍋',[['l','l'],['e','e'],['m','m'],['o','o'],['n','n']],'檸檬'],
    ['L','lake','🏞️',[['l','l'],['a','a'],['k','k'],['e','e']],'湖'],
    ['L','lock','🔒',[['l','l'],['o','o'],['ck','ck']],'鎖'],
    ['L','lunch','🍱',[['l','l'],['u','u'],['n','n'],['ch','ch']],'午餐'],
    ['L','ladder','🪜',[['l','l'],['a','a'],['d','d'],['d','d'],['er','er']],'梯'],
    ['L','ladybug','🐞',[['l','l'],['a','a'],['d','d'],['y','y'],['b','b'],['u','u'],['g','g']],'瓢蟲'],
    ['L','lollipop','🍭',[['l','l'],['o','o'],['l','l'],['l','l'],['i','i'],['p','p'],['o','o'],['p','p']],'波板糖'],
    ['M','milk','🥛',[['m','m'],['i','i'],['l','l'],['k','k']],'牛奶'],
    ['M','moon','🌙',[['m','m'],['oo','oo'],['n','n']],'月亮'],
    ['M','mouse','🐭',[['m','m'],['ou','ou'],['s','s'],['e','e']],'老鼠'],
    ['M','monkey','🐵',[['m','m'],['o','o'],['n','n'],['k','k'],['e','e'],['y','y']],'馬騮'],
    ['M','mom','👩',[['m','m'],['o','o'],['m','m']],'媽媽'],
    ['M','mask','🎭',[['m','m'],['a','a'],['s','s'],['k','k']],'面具'],
    ['M','muffin','🧁',[['m','m'],['u','u'],['f','f'],['f','f'],['i','i'],['n','n']],'鬆餅'],
    ['M','mountain','🏔️',[['m','m'],['ou','ou'],['n','n'],['t','t'],['ai','ai'],['n','n']],'山'],
    ['M','mushroom','🍄',[['m','m'],['u','u'],['sh','sh'],['r','r'],['oo','oo'],['m','m']],'蘑菇'],
    ['M','mango','🥭',[['m','m'],['a','a'],['ng','ng'],['o','o']],'芒果'],
    ['N','nest','🪺',[['n','n'],['e','e'],['s','s'],['t','t']],'巢'],
    ['N','nose','👃',[['n','n'],['o','o'],['s','s'],['e','e']],'鼻'],
    ['N','note','📝',[['n','n'],['o','o'],['t','t'],['e','e']],'字條'],
    ['N','nine','9️⃣',[['n','n'],['i','i'],['n','n'],['e','e']],'九'],
    ['N','noodle','🍜',[['n','n'],['oo','oo'],['d','d'],['l','l'],['e','e']],'麵'],
    ['N','nurse','👩‍⚕️',[['n','n'],['ur','ur'],['s','s'],['e','e']],'護士'],
    ['N','night','🌃',[['n','n'],['i','i'],['g','g'],['h','h'],['t','t']],'夜晚'],
    ['N','neck','🧣',[['n','n'],['e','e'],['ck','ck']],'頸'],
    ['N','notebook','📓',[['n','n'],['o','o'],['t','t'],['e','e'],['b','b'],['oo','oo'],['k','k']],'簿'],
    ['O','orange','🍊',[['or','or'],['a','a'],['ng','ng'],['e','e']],'橙'],
    ['O','ocean','🌊',[['o','o'],['c','c'],['ea','ea'],['n','n']],'大海'],
    ['O','octopus','🐙',[['o','o'],['c','c'],['t','t'],['o','o'],['p','p'],['u','u'],['s','s']],'八爪魚'],
    ['O','onion','🧅',[['o','o'],['n','n'],['i','i'],['o','o'],['n','n']],'洋蔥'],
    ['O','olive','🫒',[['o','o'],['l','l'],['i','i'],['v','v'],['e','e']],'橄欖'],
    ['O','oven','♨️',[['o','o'],['v','v'],['e','e'],['n','n']],'焗爐'],
    ['O','open','📂',[['o','o'],['p','p'],['e','e'],['n','n']],'打開'],
    ['P','pear','🍐',[['p','p'],['ea','ea'],['r','r']],'梨'],
    ['P','peach','🍑',[['p','p'],['ea','ea'],['ch','ch']],'桃'],
    ['P','pizza','🍕',[['p','p'],['i','i'],['z','z'],['z','z'],['a','a']],'薄餅'],
    ['P','park','🏞️',[['p','p'],['ar','ar'],['k','k']],'公園'],
    ['P','plant','🪴',[['p','p'],['l','l'],['a','a'],['n','n'],['t','t']],'植物'],
    ['P','puppy','🐶',[['p','p'],['u','u'],['p','p'],['p','p'],['y','y']],'小狗'],
    ['P','panda','🐼',[['p','p'],['a','a'],['n','n'],['d','d'],['a','a']],'熊貓'],
    ['P','pencil','✏️',[['p','p'],['e','e'],['n','n'],['c','c'],['i','i'],['l','l']],'鉛筆'],
    ['P','pillow','🛌',[['p','p'],['i','i'],['l','l'],['l','l'],['ow','ow']],'枕頭'],
    ['P','plane','✈️',[['p','p'],['l','l'],['a','a'],['n','n'],['e','e']],'飛機'],
    ['P','pool','🏊',[['p','p'],['oo','oo'],['l','l']],'泳池'],
    ['P','popcorn','🍿',[['p','p'],['o','o'],['p','p'],['c','c'],['or','or'],['n','n']],'爆谷'],
    ['P','pumpkin','🎃',[['p','p'],['u','u'],['m','m'],['p','p'],['k','k'],['i','i'],['n','n']],'南瓜'],
    ['Q','quiet','🤫',[['qu','qu'],['i','i'],['e','e'],['t','t']],'安靜'],
    ['Q','quick','⚡',[['qu','qu'],['i','i'],['ck','ck']],'快'],
    ['Q','question','❓',[['qu','qu'],['e','e'],['s','s'],['t','t'],['i','i'],['o','o'],['n','n']],'問題'],
    ['Q','quarter','🪙',[['qu','qu'],['ar','ar'],['t','t'],['er','er']],'四分一'],
    ['R','rain','🌧️',[['r','r'],['ai','ai'],['n','n']],'雨'],
    ['R','rocket','🚀',[['r','r'],['o','o'],['ck','ck'],['e','e'],['t','t']],'火箭'],
    ['R','robot','🤖',[['r','r'],['o','o'],['b','b'],['o','o'],['t','t']],'機械人'],
    ['R','rose','🌹',[['r','r'],['o','o'],['s','s'],['e','e']],'玫瑰'],
    ['R','ring','💍',[['r','r'],['i','i'],['ng','ng']],'戒指'],
    ['R','rice','🍚',[['r','r'],['i','i'],['c','c'],['e','e']],'飯'],
    ['R','road','🛣️',[['r','r'],['oa','oa'],['d','d']],'路'],
    ['R','rock','🪨',[['r','r'],['o','o'],['ck','ck']],'石頭'],
    ['R','rabbit','🐰',[['r','r'],['a','a'],['b','b'],['b','b'],['i','i'],['t','t']],'兔'],
    ['R','radio','📻',[['r','r'],['a','a'],['d','d'],['i','i'],['o','o']],'收音機'],
    ['S','sock','🧦',[['s','s'],['o','o'],['ck','ck']],'襪'],
    ['S','sand','🏖️',[['s','s'],['a','a'],['n','n'],['d','d']],'沙'],
    ['S','soap','🧼',[['s','s'],['oa','oa'],['p','p']],'番梘'],
    ['S','soup','🍲',[['s','s'],['ou','ou'],['p','p']],'湯'],
    ['S','star','⭐',[['s','s'],['t','t'],['ar','ar']],'星星'],
    ['S','snake','🐍',[['s','s'],['n','n'],['a','a'],['k','k'],['e','e']],'蛇'],
    ['S','spoon','🥄',[['s','s'],['p','p'],['oo','oo'],['n','n']],'匙羹'],
    ['S','snail','🐌',[['s','s'],['n','n'],['ai','ai'],['l','l']],'蝸牛'],
    ['S','seal','🦭',[['s','s'],['ea','ea'],['l','l']],'海豹'],
    ['S','ship','🚢',[['sh','sh'],['i','i'],['p','p']],'船'],
    ['S','shoe','👟',[['sh','sh'],['o','o'],['e','e']],'鞋'],
    ['S','shirt','👕',[['sh','sh'],['ir','ir'],['t','t']],'恤衫'],
    ['S','slide','🛝',[['s','s'],['l','l'],['i','i'],['d','d'],['e','e']],'滑梯'],
    ['S','swing','🎢',[['s','s'],['w','w'],['i','i'],['ng','ng']],'鞦韆'],
    ['S','snow','❄️',[['s','s'],['n','n'],['ow','ow']],'雪'],
    ['T','tree','🌳',[['t','t'],['r','r'],['ee','ee']],'樹'],
    ['T','truck','🚚',[['t','t'],['r','r'],['u','u'],['ck','ck']],'貨車'],
    ['T','train','🚆',[['t','t'],['r','r'],['ai','ai'],['n','n']],'火車'],
    ['T','tiger','🐯',[['t','t'],['i','i'],['g','g'],['er','er']],'老虎'],
    ['T','turtle','🐢',[['t','t'],['ur','ur'],['t','t'],['l','l'],['e','e']],'龜'],
    ['T','toast','🍞',[['t','t'],['oa','oa'],['s','s'],['t','t']],'多士'],
    ['T','tomato','🍅',[['t','t'],['o','o'],['m','m'],['a','a'],['t','t'],['o','o']],'番茄'],
    ['T','tooth','🦷',[['t','t'],['oo','oo'],['th','th']],'牙'],
    ['T','towel','🧺',[['t','t'],['ow','ow'],['e','e'],['l','l']],'毛巾'],
    ['T','tent','⛺',[['t','t'],['e','e'],['n','n'],['t','t']],'帳幕'],
    ['T','table','🪑',[['t','t'],['a','a'],['b','b'],['l','l'],['e','e']],'檯'],
    ['T','taxi','🚕',[['t','t'],['a','a'],['x','x'],['i','i']],'的士'],
    ['U','umbrella','☂️',[['u','u'],['m','m'],['b','b'],['r','r'],['e','e'],['l','l'],['l','l'],['a','a']],'遮'],
    ['U','uniform','👕',[['u','u'],['n','n'],['i','i'],['f','f'],['or','or'],['m','m']],'校服'],
    ['U','unicorn','🦄',[['u','u'],['n','n'],['i','i'],['c','c'],['or','or'],['n','n']],'獨角獸'],
    ['U','under','⬇️',[['u','u'],['n','n'],['d','d'],['er','er']],'下面'],
    ['V','violin','🎻',[['v','v'],['i','i'],['o','o'],['l','l'],['i','i'],['n','n']],'小提琴'],
    ['V','volcano','🌋',[['v','v'],['o','o'],['l','l'],['c','c'],['a','a'],['n','n'],['o','o']],'火山'],
    ['V','vacuum','🧹',[['v','v'],['a','a'],['c','c'],['u','u'],['u','u'],['m','m']],'吸塵機'],
    ['V','vase','🏺',[['v','v'],['a','a'],['s','s'],['e','e']],'花樽'],
    ['V','video','📹',[['v','v'],['i','i'],['d','d'],['e','e'],['o','o']],'影片'],
    ['W','water','💧',[['w','w'],['a','a'],['t','t'],['er','er']],'水'],
    ['W','watch','⌚',[['w','w'],['a','a'],['t','t'],['ch','ch']],'手錶'],
    ['W','worm','🪱',[['w','w'],['or','or'],['m','m']],'蟲'],
    ['W','wolf','🐺',[['w','w'],['o','o'],['l','l'],['f','f']],'狼'],
    ['W','window','🪟',[['w','w'],['i','i'],['n','n'],['d','d'],['ow','ow']],'窗'],
    ['W','wagon','🛒',[['w','w'],['a','a'],['g','g'],['o','o'],['n','n']],'手推車'],
    ['W','whale','🐋',[['wh','wh'],['a','a'],['l','l'],['e','e']],'鯨'],
    ['W','watermelon','🍉',[['w','w'],['a','a'],['t','t'],['er','er'],['m','m'],['e','e'],['l','l'],['o','o'],['n','n']],'西瓜'],
    ['X','mix','🥣',[['m','m'],['i','i'],['x','x']],'拌'],
    ['X','xray','🩻',[['x','x'],['r','r'],['ay','ay']],'X光'],
    ['X','axle','⚙️',[['a','a'],['x','x'],['l','l'],['e','e']],'車軸'],
    ['Y','yogurt','🥛',[['y','y'],['o','o'],['g','g'],['ur','ur'],['t','t']],'乳酪'],
    ['Y','yoyo','🪀',[['y','y'],['oy','oy'],['o','o']],'搖搖'],
    ['Y','yellow','💛',[['y','y'],['e','e'],['l','l'],['l','l'],['ow','ow']],'黃色'],
    ['Y','yarn','🧶',[['y','y'],['ar','ar'],['n','n']],'毛線'],
    ['Z','zigzag','⚡',[['z','z'],['i','i'],['g','g'],['z','z'],['a','a'],['g','g']],'之字'],
    ['Z','zucchini','🥒',[['z','z'],['u','u'],['c','c'],['ch','ch'],['i','i'],['n','n'],['i','i']],'青瓜'],
    ['Z','zap','⚡',[['z','z'],['a','a'],['p','p']],'閃電'],
];

function vocabRow(r) {
    let ssml = `<speak><emphasis level="strong">${r[0]}</emphasis>.<break time="1s"/>`;
    let phases = [{t:0, type:'letter', text: r[0]}];
    let curT = 1500;
    let phonics = r[3] || [];
    let phonicsData = phonics.map(ph => ({ ipa: `/${ph[0]}/`, letter: ph[1] }));
    phonics.forEach((ph, index) => {
        ssml += `<phoneme alphabet="ipa" ph="${ph[0]}">${ph[1]}</phoneme><break time="1s"/>`;
        phases.push({t: curT, type:'phonic', pData: phonicsData, hlIdx: index});
        curT += 1300;
    });
    ssml += `${r[1]}.</speak>`;
    var img = (r[4] && /^https?:/.test(String(r[4]))) ? r[4] : null;
    var yue = r[5] || (!img && r[4] ? r[4] : '') || '';
    phases.push({t: curT, type:'word', text: r[1].toUpperCase(), emoji: r[2], img: img});
    return { l: r[0], w: r[1], emoji: r[2], ssml: ssml, p: phases, st: letterStrokes[r[0]], yue: yue };
}

const D = rawD.concat(rawMore).map(vocabRow);

// Expose on window so modules that read window.D / window.letterStrokes work
// (top-level const is not attached to window in browsers).
window.phonicsGroups = phonicsGroups;
window.letterStrokes = letterStrokes;
window.D = D;

window._baseVocabLen = window.D.length;
