// ==========================================
// Kid-friendly word stories (Cantonese environment)
// Not Latin/Greek roots — picture, sound, and HK loanwords
// ==========================================

window.WORD_STORIES = {
    ant:   { yue: '螞蟻', story: '好似一隊好細隻嘅兵。英文 ant，開頭 a 讀「呀」。' },
    axe:   { yue: '斧頭', story: '劈柴嘅斧頭。axe 聽落好似「吖士」，好大力。' },
    arm:   { yue: '手臂', story: '你條手臂好有力。arm 開頭 a，好似「呀」一聲舉起手。' },
    art:   { yue: '畫畫', story: '畫畫、整靚嘢就叫 art。art 好似「呀」完再 t。' },
    bug:   { yue: '蟲蟲', story: '細細隻蟲蟲。bug 開頭 b，好似把嘴噴一啖「b」。' },
    bat:   { yue: '蝙蝠', story: '夜晚飛嘅蝙蝠。bat 同 cat 差一個音，b 噴氣、c 係「k」。' },
    bed:   { yue: '床', story: '瞓覺張床。bed 開頭 b，躺低就 bed。' },
    bus:   { yue: '巴士', story: '香港人叫「巴士」，英文就係 bus，聽落好似「巴士」！' },
    cat:   { yue: '貓貓', story: '喵喵叫嘅貓。cat 開頭 c 讀「k」，好似「卡」一下。' },
    cup:   { yue: '杯', story: '飲水個杯。cup 好似「卡噗」倒水聲。' },
    car:   { yue: '車', story: '馬路上架車。car 開頭 c 讀「k」，好似「卡」開出去。' },
    cap:   { yue: '帽', story: '戴喺頭嗰頂帽。cap 同 cup 差少少，cap 係帽、cup 係杯。' },
    dog:   { yue: '狗仔', story: '汪汪叫嘅狗。dog 開頭 d，舌頭彈一下「d」。' },
    dad:   { yue: '爸爸', story: '爸爸就係 dad。兩個 d，好似叫「爹、爹」。' },
    dot:   { yue: '圓點', story: '細細粒圓點。dot 好似「啄」一下，啄出一點。' },
    duck:  { yue: '鴨仔', story: '游水嘅鴨。duck 開頭 d，嘎嘎叫。' },
    egg:   { yue: '雞蛋', story: '圓碌碌雞蛋。egg 開頭 e 讀「欸」，好似打開蛋「欸」。' },
    elf:   { yue: '小精靈', story: '童話入面嘅小精靈。elf 好似好輕、好細隻。' },
    elk:   { yue: '大鹿', story: '頭上有角嘅大鹿。elk 同 elf 差一個音，elk 大隻啲。' },
    eat:   { yue: '食嘢', story: '張嘴食嘢就叫 eat。ea 拉長「衣」音。' },
    fox:   { yue: '狐狸', story: '精精地狐狸。fox 尾音 x 讀「ks」，好似「科克斯」。' },
    fan:   { yue: '風扇', story: '吹涼風扇。fan 開頭 f，好似風「呼」一聲。' },
    fin:   { yue: '魚鰭', story: '魚游水嗰塊鰭。fin 開頭 f，魚擺嚟擺去。' },
    fog:   { yue: '霧', story: '白蒙蒙大霧。fog 開頭 f，好似「呼」出一口霧。' },
    gum:   { yue: '香口膠', story: '香港人有時叫 gum。chew chew 香口膠，gum 開頭 g。' },
    gas:   { yue: '汽油', story: '車要用嘅汽油。gas 開頭 g，「加」油喇。' },
    gift:  { yue: '禮物', story: '生日收到嘅禮物。gift 開頭 g，好似「給」你一份。' },
    goat:  { yue: '山羊', story: '咩咩叫山羊。goat 中間 oa 拉長「oh」。' },
    hat:   { yue: '帽', story: '戴喺頭上嘅帽。hat 開頭 h，好似哈一口氣戴帽。' },
    hen:   { yue: '母雞', story: '生蛋嘅雞。hen 開頭 h，咯咯咯。' },
    hit:   { yue: '打一下', story: '輕輕打一下。hit 開頭 h，好似「呵」一聲打中。' },
    hop:   { yue: '跳一跳', story: '單腳跳。hop 好似袋鼠「hop hop」跳。' },
    ink:   { yue: '墨水', story: '筆入面嘅墨水。ink 開頭 i 讀「衣」，黑墨水。' },
    ice:   { yue: '冰', story: '凍冰冰。ice 香港有時講「哎士」，好似雪糕 ice cream。' },
    ill:   { yue: '病咗', story: '唔舒服、病咗。ill 兩個 l，躺低休息。' },
    insect:{ yue: '昆蟲', story: '細細隻昆蟲。in-sect，好似「入」咗草裏面。' },
    jam:   { yue: '果醬', story: '塗麵包嘅果醬。jam 開頭 j 讀「遮」，甜甜地。' },
    jet:   { yue: '飛機', story: '飛得好快嘅噴射機。jet 開頭 j，嗖一聲飛走。' },
    jog:   { yue: '慢跑', story: '慢慢跑步。jog 開頭 j，jog jog 跑。' },
    jug:   { yue: '水壺', story: '裝水個壺。jug 開頭 j，倒水「咕咕」。' },
    kid:   { yue: '小朋友', story: '你就係 kid！kid 開頭 k，叻叻小朋友。' },
    kit:   { yue: '工具盒', story: '一盒工具。kit 開頭 k，打開工具盒。' },
    keg:   { yue: '木桶', story: '圓碌碌大桶。keg 開頭 k，好重。' },
    king:  { yue: '國王', story: '戴皇冠嘅國王。king 尾音 ng，好似「興」。' },
    log:   { yue: '木頭', story: '圓碌碌木頭。log 開頭 l，舌頭向上「l」。' },
    leg:   { yue: '腳', story: '行路嗰條腳。leg 開頭 l，踢一踢。' },
    lip:   { yue: '嘴唇', story: '食嘢嗰兩片唇。lip 開頭 l，抿一抿嘴。' },
    lamp:  { yue: '燈', story: '發光盞燈。lamp 開頭 l，啪一聲開燈。' },
    map:   { yue: '地圖', story: '搵路用地圖。map 開頭 m，抿嘴「mmm」。' },
    man:   { yue: '男人', story: '大個男人。man 開頭 m，好似叫「嘛」。' },
    mat:   { yue: '地墊', story: '坐或者瞓嗰張墊。mat 開頭 m，軟軟地。' },
    mug:   { yue: '大杯', story: '飲茶大杯。mug 開頭 m，兩手捧住。' },
    net:   { yue: '網', story: '接波個網。net 開頭 n，網住佢。' },
    nut:   { yue: '堅果', story: '硬殼堅果。nut 開頭 n，咬一口「咔」。' },
    nap:   { yue: '小睡', story: '瞓一陣午覺。nap 開頭 n，眼核核。' },
    nail:  { yue: '釘子', story: '釘嘢嘅釘子。nail 中間 ai 拉長「欸」。' },
    ox:    { yue: '牛', story: '大力牛。ox 尾音 x 讀「ks」，好似「喔克斯」。' },
    owl:   { yue: '貓頭鷹', story: '夜晚咕咕叫。owl 開頭 ow 好似「噢」。' },
    oil:   { yue: '油', story: '煮嘢用嘅油。oil 開頭 oi，滑溜溜。' },
    oak:   { yue: '橡樹', story: '好高大棵樹。oak 中間 oa 拉長「oh」。' },
    pig:   { yue: '豬仔', story: '肥肥豬仔。pig 開頭 p，噴氣「p」。' },
    pan:   { yue: '平底鍋', story: '煎嘢個鍋。pan 開頭 p，啪一聲落鑊。' },
    pot:   { yue: '煲', story: '煲湯個煲。pot 開頭 p，咕嘟咕嘟。' },
    pen:   { yue: '筆', story: '寫字支筆。pen 開頭 p，點一下寫。' },
    queen: { yue: '皇后', story: '戴皇冠嘅皇后。qu 永遠一齊讀「kw」，queen。' },
    quack: { yue: '鴨叫聲', story: '鴨叫 quack quack。qu 讀「kw」，好似「呱」。' },
    quiz:  { yue: '小測驗', story: '答問題小測驗。quiz 開頭 qu，考考你。' },
    quilt: { yue: '被舖', story: '暖笠笠張被。quilt 開頭 qu，蓋住瞓。' },
    rat:   { yue: '老鼠', story: '吱吱老鼠。rat 開頭 r，舌頭震「rrr」。' },
    red:   { yue: '紅色', story: '紅紅嘅顏色。red 開頭 r，好似紅燈。' },
    run:   { yue: '跑', story: '快快跑。run 開頭 r，跑跑跑。' },
    rug:   { yue: '地毯', story: '地下張氈。rug 開頭 r，踩上去軟軟。' },
    sun:   { yue: '太陽', story: '天上個太陽。sun 開頭 s，曬得暖暖「sss」。' },
    sad:   { yue: '傷心', story: '喊喊地傷心。sad 開頭 s，嘴角向下。' },
    sit:   { yue: '坐下', story: '坐低。sit 開頭 s，屁股坐下。' },
    six:   { yue: '六', story: '數字六。six 尾音 x 讀「ks」，數手指：六！' },
    toy:   { yue: '玩具', story: '好玩玩具。toy 開頭 t，叮一聲玩。' },
    ten:   { yue: '十', story: '十隻手指。ten 開頭 t，數到十。' },
    tap:   { yue: '水龍頭', story: '出水水龍頭。tap 開頭 t，擰開 tap。' },
    tub:   { yue: '浴缸', story: '沖涼個缸。tub 開頭 t，浸住沖涼。' },
    up:    { yue: '向上', story: '手指向上。up 開頭 u 讀「啊」，升上去。' },
    urn:   { yue: '瓶子', story: '圓身瓶子。urn 開頭 ur，好似「呃」一聲。' },
    ufo:   { yue: '飛碟', story: '外星人飛碟 UFO。三個字母 U-F-O，好似飛碟。' },
    uncle: { yue: '叔叔', story: '香港有人叫「安哥」，英文 uncle 聽落好似「安哥」。' },
    van:   { yue: '客貨車', story: '香港人叫 van。van 開頭 v，咬住下唇「v」。' },
    vet:   { yue: '獸醫', story: '醫動物嘅醫生。vet 開頭 v，幫狗貓睇病。' },
    vine:  { yue: '藤蔓', story: '爬牆嘅藤。vine 中間 i 拉長「哎」。' },
    vest:  { yue: '背心', story: '冇袖背心。vest 開頭 v，套上身。' },
    web:   { yue: '蜘蛛網', story: '蜘蛛織網。web 開頭 w，圓圓張網。' },
    wig:   { yue: '假髮', story: '戴喺頭假髮。wig 開頭 w，換個造型。' },
    wet:   { yue: '濕咗', story: '水濺到濕咗。wet 開頭 w，滴滴水。' },
    win:   { yue: '贏咗', story: '比賽贏咗。win 開頭 w，舉杯贏。' },
    box:   { yue: '盒子', story: '裝嘢個盒。box 尾音 x 讀「ks」，打開盒。' },
    wax:   { yue: '蠟', story: '蠟燭嘅蠟。wax 尾音 x 讀「ks」，融咗亮亮。' },
    yam:   { yue: '蕃薯', story: '甜甜蕃薯。yam 開頭 y 讀「呀」，好似「吖」。' },
    yak:   { yue: '氂牛', story: '毛茸茸大牛。yak 開頭 y，高山上面。' },
    yell:  { yue: '大叫', story: '大聲叫。yell 開頭 y，啊啊叫。' },
    yolk:  { yue: '蛋黃', story: '雞蛋中間黃黃。yolk 開頭 y，圓圓黃心。' },
    zip:   { yue: '拉鏈', story: '衫嘅拉鏈。zip 開頭 z，zzzz 拉上去。' },
    zoo:   { yue: '動物園', story: '睇動物嘅園。zoo 開頭 z，香港人都識 zoo！' },
    zebra: { yue: '斑馬', story: '黑白間斑馬。zebra 開頭 z，一間一間。' },
    zero:  { yue: '零', story: '數字零。zero 開頭 z，圓圓一個 0。' }
};

window.LETTER_HINTS = {
    A: 'A 好似尖尖座山，中間再加一條橫。',
    B: 'B 先畫直柱，再畫上圓下圓兩個肚。',
    C: 'C 好似開口個月亮，唔使封口。',
    D: 'D 先畫直柱，再由上畫到下一個大彎。',
    E: 'E 直柱加三條橫：上、中、下。',
    F: 'F 好似冇底嘅 E，得上同中兩條橫。',
    G: 'G 先畫 C，再向入加一條短橫。',
    H: 'H 兩條直柱，中間一條橋。',
    I: 'I 上橫、中間直、下橫，好似一個人企喺度。',
    J: 'J 上橫，再向下彎個鈎。',
    K: 'K 直柱，再加向上同向下兩隻腳。',
    L: 'L 向下再向右，好似張凳。',
    M: 'M 兩座山連住，中間跌落再上。',
    N: 'N 左直、斜線、右直。',
    O: 'O 圓圓一個圈，頭尾接返。',
    P: 'P 直柱加上面一個圓肚。',
    Q: 'Q 圓圈再加一條尾。',
    R: 'R 好似 P，再加一隻向下斜腳。',
    S: 'S 好似條蛇，上彎下彎。',
    T: 'T 上面一條橫，中間插支直。',
    U: 'U 好似個杯，兩邊直中間彎。',
    V: 'V 好似倒轉座山。',
    W: 'W 兩個 V 連住。',
    X: 'X 兩條斜線交叉。',
    Y: 'Y 上面分叉，下面一支直。',
    Z: 'Z 上橫、斜線、下橫。'
};

(function attachStoriesToVocab() {
    var list = window.D;
    var stories = window.WORD_STORIES;
    if (!list || !stories) return;
    for (var i = 0; i < list.length; i++) {
        var s = stories[list[i].w];
        if (s) {
            list[i].yue = s.yue;
            list[i].story = s.story;
        }
    }
})();
